### ISSUE TITLE
Potential bug with Koios gRest could not find a couple pools.

### ISSUE THREAD

**Issue by Jack-0** [cardano-community/guild-operators#1465] opened 2022-07-23 17:35 UTC
**Describe the bug**
I've just queried 
```https://api.koios.rest/api/v0/pool_list?offset=${offset}&limit=500```
using pagination (ofc) to get all pool data.

However when filtering the list I noticed a pool is missing from the list and I believe this might be a bug or a corrupt db-sync.

**To Reproduce**
1. Use pagination to query all pools at this endpoint ```https://api.koios.rest/api/v0/pool_list?```
2. Filter list for the pool with ticker MAPLE (also tried with both values converted to uppercase)
3. pools are not found also tried filtering by bech32 pool id with no luck

**Expected behavior**
Expected to find those two pools

**Additional context**
Check out this commit to see the code I wrote to find this error. 
https://github.com/pixel-pool/f2lb-backend/commit/5d7edeffbf32f98c4f7472985ccae34a8b108e92

**Comment by Jack-0** [comment] 2022-07-23 17:35
Note: I checked the pools existed via multiple other sources before creating this issue :)

**Comment by Jack-0** [comment] 2022-07-23 18:30
Update: 
I've found that the ticker appears to be null. A few other tickers returned from this api endpoint are also null.

**Comment by dostrelith678** [comment] 2022-07-23 19:21
Thanks for reporting, I can confirm at least on my instance pool_info does not return proper meta stuff for this pool:

```
cexplorer=# select * from grest.pool_info('{pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n}');
-[ RECORD 1 ]---+-------------------------------------------------------------------------------------------------------------
pool_id_bech32  | pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n
pool_id_hex     | 30539a022c8f4c393707bc4ebef7a58a4608eca14e5c6b5746a8f524
active_epoch_no | 354
vrf_key_hash    | 749bb0ceadbec4a31228b45262febd8bb1035f3b31ee89affecc042938245555
margin          | 0.03
fixed_cost      | 340000000
pledge          | 100000000
reward_addr     | stake1u9mvnhuxelnhf9fsxkvfz02q7efnmtpqnke9k7lmechnu9gcucs7x
owners          | {stake1u9mvnhuxelnhf9fsxkvfz02q7efnmtpqnke9k7lmechnu9gcucs7x}
relays          | {"{\"dns\": \"relay1.cardanomapleleaf.ca\", \"srv\": null, \"ipv4\": null, \"ipv6\": null, \"port\": 7003}"}
meta_url        | https://raw.githubusercontent.com/IanChok/MapleLeafPool/main/p
meta_hash       | 603b5c78a8f5a8d0a4e7eb4189734fd9655ef0a9633d7ed1bba828cc06f78343
meta_json       |
pool_status     | registered
retiring_epoch  |
op_cert         |
op_cert_counter |
active_stake    | 109619674
block_count     |
live_pledge     | 107646573
live_stake      | 107646573
live_delegators | 1
live_saturation | 0.00
```

`meta_json` field being empty, but the `meta_url` seems legit (althugh perhaps db-sync thinks otherwise?). This data should come from the `pool_offline_data` db-sync table. Will need to investigate further to see what the real issue is.

**Comment by rdlrt** [comment] 2022-07-24 01:58
Could be a nice uncommon case, [4 attempts](https://api.koios.rest/api/v0/pool_updates?_pool_bech32=pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n) made within an epoch 😄 , might tie into back-and-forth meta updates that we had few weeks ago (the query for which wasn't efficient as  pod.pmr_id vs meta_id cannot be relied upon to use latest mapping, needs to drilled down to tx_id to use for sorting)

**Comment by rdlrt** [comment] 2022-07-25 05:06
Just checked for the pool in question.

Metadata reference is good:
``` sql
 select * from pool_metadata_ref where pool_id = (select id from pool_hash where view = 'pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n') order by id desc LIMIT 1;
  id   | pool_id |                              url                               |                                hash                                | registered_tx_id
-------+---------+----------------------------------------------------------------+--------------------------------------------------------------------+------------------
 28259 |   17944 | https://raw.githubusercontent.com/IanChok/MapleLeafPool/main/p | \x603b5c78a8f5a8d0a4e7eb4189734fd9655ef0a9633d7ed1bba828cc06f78343 |         47155264
(1 row)
```

Pool offline data is not yet populated by SMASH module:
``` sql
select * from pool_offline_data where pmr_id=28259;
 id | pool_id | ticker_name | hash | json | bytes | pmr_id
----+---------+-------------+------+------+-------+--------
(0 rows)
```

The last data available in pool_offline_data for given pool (note that this should **NOT** be used as there are later updates from pool that havent been refreshed by smash yet):
``` sql
select id,pmr_id,ticker_name from pool_offline_data where pool_id=(select id from pool_hash where view = 'pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n');;
  id   | pmr_id | ticker_name
-------+--------+-------------
 11622 |  17889 | MAPLE
(1 row)
```

To be sure, the mentioned metadata ID (i.e. `28259`) has NOT yet resulted in an error yet:
``` sql
select id,pmr_id,fetch_error,retry_count from pool_offline_fetch_error where pool_id = (select id from pool_hash where view = 'pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n') ORDER BY ID DESC LIMIT 5;
   id    | pmr_id |                                                                                         fetch_error                                                                                          | retry_count
---------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------
 8530936 |  28257 | URL parse error from for pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n resulted in : InvalidUrlException "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n" "Invalid URL" |          91
 8528314 |  28257 | URL parse error from for pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n resulted in : InvalidUrlException "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n" "Invalid URL" |          90
 8527097 |  28257 | URL parse error from for pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n resulted in : InvalidUrlException "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n" "Invalid URL" |          89
 8525926 |  28257 | URL parse error from for pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n resulted in : InvalidUrlException "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n" "Invalid URL" |          88
 8521339 |  28257 | URL parse error from for pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n resulted in : InvalidUrlException "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n" "Invalid URL" |          87
(5 rows)
```

All of the above suggests what query is doing is expected, if/when `pool_offline_data` does get populated, the pool_info and pool_list should automatically show correct values (also why it's not a good idea to expire old metadata until newer one is reflected).

**Comment by Jack-0** [comment] 2022-07-30 11:10
This api also receives null metadata. 
```
curl 'https://api.koios.rest/api/v0/pool_metadata' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://api.koios.rest' \
  -H 'Referer: https://api.koios.rest/' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  --data-raw $'{\n  "_pool_bech32_ids": [\n    "pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n"\n  ]\n}' \
  --compressed
```
```
[{"pool_id_bech32":"pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n","meta_url":"https://raw.githubusercontent.com/IanChok/MapleLeafPool/main/p","meta_hash":"603b5c78a8f5a8d0a4e7eb4189734fd9655ef0a9633d7ed1bba828cc06f78343","meta_json":null}]
```

Not sure where to go from here personally I believe the old metadata should be kept until new changes are reflected from what you've mentioned. However I have not looked at the Koios backend. 

If you would refer me to the codebase I'll do some exploring myself.  Got a db-sync node that's nearly synced up :)

**Comment by rdlrt** [comment] 2022-07-30 11:25
>  I believe the old metadata should be kept until new changes are reflected

The problem isnt the code, it's about conflict of opinions about whether this should be reflected IMO. As a SPO, one should not remove their old metadata until newer one if reflected (which ofcourse - involves ensuring new and old URLs are different alongwith hash). Over the years,  countless support confusions for new SPOs has been looking at certain source showing their metadata (cached from old one) as valid, while their newer one being invalid causing them false assumption of their meta being correct and raising tickets on different providers/explorers.

Besides - showing old metadata would be incorrect and false representation. There are design decisions in SMASH where they do not want to poll offline URLs too often - besides, a newer pool metadata being updated could be wrong - which will not be known until pod reaches polling. This starts a web of back-and-forth on user end (resulting in exactly what you see above for MAPLE pool).

There is pool_updates endpoint which gives historical view (currently contains meta_url, meta_hash), if old pool metadata is required - IMO, a feature request is better against that endpoint to keep data representation truthful to show what dbsync knows (and not complicated scenario)?

**Comment by rdlrt** [comment] 2022-08-05 06:56
Closing in favour of linked issue as per last comment above

**Closed by rdlrt** 2022-08-05 06:56 UTC
Labels: support

**Comment by Jack-0** [comment] 2022-10-09 19:57
There is still an issue here. I've been writing an API that checks pools unfortunately some of the data is null for certain tickers. Including that same ticker mentioned above... 

# Reproduce
1. fetch all data from https://api.koios.rest/#get-/pool_list 
2. Notice that some fields are null
3. **here are some pools that have a null ticker**

```
high: pool1tay8z4sq4a4gmyhnygyt0t5j84z8epwjra06wq28jnnmschkkuu 
tcatl: pool1gduk8s5stt3uej5nl9vs7marx8jjyeadwz3505gzvuqey2lch35 
zebra: pool16sm29hg3qrk5lyp74qcljt38l86v5zvg95395h9gqrn6qe97d9z 
maple: pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n 
```

Is this expect behavior for Koios? 

# Context 
I know it maybe possible to find this data from pool history using the pool bech32. However, the challenge I face is I want to get a pools info when only knowing it's ticker. If some tickers are null this is not achievable as far as I am aware with Koios.

1. I query all ~3000 pools. 
2. I filter the list by ticker
3. As a few entries are null, I never find the target pool

This could be classed as a **feature** if this is the expected behavior of Koios. However, other sites/api's still display the pools tickers the only issue I found was with [high] on Cardanoscan.io

### If you don't classify this as a bug could this be turned into a feature request. I'm opening this ticket on this issue again for context.

**Comment by rdlrt** [comment] 2022-10-09 21:34
The result from last comment is partially a mix-up...there is an issue with pool offline data in dbsync 13.0.5 (only reproduced on those who use this specific release). It has been fixed on master but a release hasn't been marked yet - will reply on new thread soon.
